<?php
namespace app\index\controller;

use think\App;
use think\Controller;

class Base extends Controller
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //if (session('clint_id')) return false;

        //每次访问都新生成clint_id，存session
        $request = request();
        $clint_ip = $request->ip();
        $time = time();
        $range = generate(5);

        $clint_id = $range.'_'.base64_encode($clint_ip.'_'.$time);
        session('clint_id', $clint_id);
    }

    public function index() {
        //return '123';
        return session('clint_id');
    }

    public function login_check() {
        $request = request();
        $clint_id = $request->get('clint_id');

    }

}